name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    name: 'Linux coverage'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install tox
      - run: tox -e coverage
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          name: boa-coverage